
// generated by lib/sync.js
module.exports = {
  trailingSlash: true,
  eslint: {
    ignoreDuringBuilds: true
  },
  env: {
      zesty: {
          instance_zuid: "", // zesty unique id of content instance
          stage: "", // e.g. https://XYZ-dev.webengine.zesty.io
          production: "", // e.g. https://www.acme.com
          stage_password: "",
          src_dir: "" // where the next project has pages, components, etc folders
      }
  }
}