/**
 * Zesty.io AutoGenerated Footer Component
 * This file is used in [...slug.js] for example. It is not necceary and may be deleted or modified as needed.
 * 
 */

function Footer() {
       
    return (
        <></>
    )
}

export default Footer;
