// generated by lib/sync.js
// This is a required an autogenerated file from the Zesty.io NextJS integration
// This file is overwritten everytime the integration script is run
    
import Homepage from './Homepage';

export {
  Homepage
}