// generated by lib/sync.js
// This is a required an autogenerated file from the Zesty.io NextJS integration
// This file is overwritten everytime the integration script is run

import Homepage from './Homepage';
import Clipping from './Clipping';
import Article from './Article';
import Author from './Author';

export { Homepage, Clipping, Article, Author };
